export const HABIT_ICON_NAMES = [
  "QuestionMark",
  "Plus",
  "Run",
  "Walk",
  "Yoga",
  "Gym",
  "Cycling",
  "Heartbeat",
  "Flame",
  "Energy",
  "Brain",
  "Book",
  "Journal",
  "Study",
  "Focus",
  "Timer",
  "Sparkles",
  "Language",
  "Moon",
  "Water",
  "Heart",
  "Apple",
  "Food",
  "Pill",
  "Dental",
  "Brush",
  "Stethoscope",
  "MoodSmile",
  "Work",
  "Calendar",
  "Checklist",
  "Mail",
  "Receipt",
  "Laptop",
  "Phone",
  "Coding",
  "Money",
  "Savings",
  "Wallet",
  "Analytics",
  "Coffee",
  "Sunrise",
  "Bath",
  "Trash",
  "Nature",
  "Music",
  "Travel",
  "Home",
  "Bed",
  "Shopping",
  "Car",
  "Social",
  "Chat",
  "Call",
  "Wind",
  "Cloud",
  "Leaf",
  "Flower",
  "Plant",
  "Star",
  "Trophy",
  "Medal",
  "Pencil",
  "Camera",
  "Palette",
  "Microphone",
  "ChefHat",
  "Gamepad",
  "Pray",
  "Stretching",
  "MoodCheck",
  "Alarm",
  "Award",
  "Football",
  "Youtube",
  "ChartLine",
  "ClipboardCheck",
  "Confetti",
  "Eye",
  "Friends",
  "Guitar",
  "Hourglass",
  "MapPin",
  "Massage",
  "MedicineSyrup",
  "News",
  "Paint",
  "Plant2",
  "Scale",
  "Shirt",
  "Soup",
  "Swimming",
  "Tools",
  "UserHeart",
  "Wash",
  "Writing",
  "Zzz",
] as const;

export type HabitIconName = (typeof HABIT_ICON_NAMES)[number];

export type HabitIconCategory = {
  label: string;
  iconNames: HabitIconName[];
};

export const HABIT_ICON_CATEGORIES: HabitIconCategory[] = [
  {
    label: "Fitness",
    iconNames: [
      "Run",
      "Walk",
      "Yoga",
      "Gym",
      "Cycling",
      "Heartbeat",
      "Flame",
      "Energy",
      "Stretching",
      "Football",
      "Swimming",
    ],
  },
  {
    label: "Mind and Learning",
    iconNames: [
      "Brain",
      "Book",
      "Journal",
      "Study",
      "Focus",
      "Timer",
      "Sparkles",
      "Language",
      "Pencil",
      "Writing",
      "News",
      "Youtube",
    ],
  },
  {
    label: "Health",
    iconNames: [
      "Moon",
      "Water",
      "Heart",
      "Apple",
      "Food",
      "Pill",
      "Dental",
      "Brush",
      "Stethoscope",
      "MoodSmile",
      "Scale",
      "MedicineSyrup",
      "UserHeart",
      "Eye",
      "Zzz",
    ],
  },
  {
    label: "Productivity",
    iconNames: [
      "Work",
      "Calendar",
      "Checklist",
      "Mail",
      "Receipt",
      "Laptop",
      "Phone",
      "Coding",
      "ClipboardCheck",
      "ChartLine",
      "Hourglass",
      "Alarm",
    ],
  },
  {
    label: "Finance",
    iconNames: ["Money", "Savings", "Wallet", "Analytics", "Award"],
  },
  {
    label: "Lifestyle",
    iconNames: [
      "Coffee",
      "Sunrise",
      "Bath",
      "Trash",
      "Nature",
      "Music",
      "Travel",
      "Home",
      "Bed",
      "Shopping",
      "Car",
      "ChefHat",
      "Soup",
      "Wash",
      "Shirt",
      "Tools",
      "MapPin",
      "Massage",
    ],
  },
  {
    label: "Social",
    iconNames: ["Social", "Chat", "Call", "Friends", "UserHeart"],
  },
  {
    label: "Nature",
    iconNames: ["Wind", "Cloud", "Leaf", "Flower", "Plant", "Plant2"],
  },
  {
    label: "Creative",
    iconNames: ["Camera", "Palette", "Microphone", "Paint", "Guitar"],
  },
  {
    label: "Achievements",
    iconNames: ["Star", "Trophy", "Medal", "Gamepad", "Pray", "MoodCheck", "Confetti"],
  },
];

export const HABIT_COLORS = [
  { name: "Blue", value: "#3b82f6" },
  { name: "Green", value: "#34d399" },
  { name: "Classic Green", value: "#10b981" },
  { name: "Rose", value: "#f43f5e" },
  { name: "Amber", value: "#f59e0b" },
  { name: "Violet", value: "#8b5cf6" },
  { name: "Cyan", value: "#06b6d4" },
  { name: "Indigo", value: "#6366f1" },
  { name: "Lime", value: "#84cc16" },
  { name: "Pink", value: "#ec4899" },
  { name: "Emerald", value: "#22c55e" },
  { name: "Sky", value: "#0ea5e9" },
  { name: "Teal", value: "#14b8a6" },
  { name: "Fuchsia", value: "#d946ef" },
  { name: "Slate", value: "#64748b" },

  // New
  { name: "Purple", value: "#a855f7" },
  { name: "Mint", value: "#2dd4bf" },
  { name: "Lavender", value: "#c084fc" },
  { name: "Coral", value: "#fb7185" },
  { name: "Peach", value: "#fdba74" },
  { name: "Ice", value: "#67e8f9" },
  { name: "Neon Green", value: "#4ade80" },
  { name: "Electric Blue", value: "#38bdf8" },
  { name: "Deep Purple", value: "#7c3aed" },
  { name: "Cherry", value: "#e11d48" },
  { name: "Ocean", value: "#0891b2" },
  { name: "Sunset", value: "#f97316" },
  { name: "Gold", value: "#eab308" },
  { name: "Ruby", value: "#dc2626" },
  { name: "Aqua", value: "#22d3ee" },
] as const;

export type HabitColorValue = (typeof HABIT_COLORS)[number]["value"];

export const UNIT_GROUPS = [
  {
    label: "Scalar",
    units: [
      "times",
      "steps",
      "reps",
      "sets",
      "pages",
      "chapters",
      "items",
      "words",
      "articles",
    ],
  },
  { label: "Mass", units: ["kilograms", "grams", "pounds", "milligrams"] },
  {
    label: "Volume",
    units: ["liters", "milliliters", "cups", "gallons", "ounces"],
  },
  {
    label: "Duration",
    units: ["seconds", "minutes", "hours", "days", "weeks"],
  },
  { label: "Energy", units: ["calories", "kilocalories", "kilojoules"] },
  {
    label: "Length",
    units: ["kilometers", "meters", "miles", "feet", "inches", "yards"],
  },
  { label: "Hydration", units: ["glasses", "bottles", "cups"] },
  {
    label: "Finance",
    units: ["rupees", "dollars", "savings entries", "transactions"],
  },
  {
    label: "Focus",
    units: ["pomodoros", "sessions", "blocks", "tasks", "lessons"],
  },
  {
    label: "Wellness",
    units: ["servings", "meals", "medications", "breaths", "moods"],
  },
  {
    label: "Creative",
    units: ["photos", "sketches", "songs", "drafts", "ideas"],
  },
] as const;
