import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";

const geistSans = Geist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Habitoo",
  description: "Generated by create next app",
  icons: "/habits.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
    lang="en"
    className={`${geistSans.className} antialiased `}
    suppressHydrationWarning
    >
        <body className="bg-gray-100 dark:bg-zinc-950">
          <ClerkProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <TooltipProvider delayDuration={0} skipDelayDuration={0}>
                <Toaster position="top-center"/>
                {children}
              </TooltipProvider>
            </ThemeProvider>
          </ClerkProvider>
        </body>
      </html>
  );
}
