import {
  HABIT_COLORS,
  HABIT_ICON_CATEGORIES,
  UNIT_GROUPS,
  type HabitIconName,
} from "@habitoo/core";
import type { ComponentType, ElementType } from "react";
import {
  IconAlarm,
  IconApple,
  IconAward,
  IconBallFootball,
  IconBarbell,
  IconBath,
  IconBed,
  IconBike,
  IconBolt,
  IconBook,
  IconBrain,
  IconBriefcase,
  IconBrush,
  IconCalendarEvent,
  IconCamera,
  IconCar,
  IconChartBar,
  IconChartLine,
  IconChecklist,
  IconChefHat,
  IconClockHour4,
  IconClipboardCheck,
  IconCloud,
  IconCode,
  IconCoffee,
  IconConfetti,
  IconCurrencyDollar,
  IconDental,
  IconDeviceGamepad2,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconDroplet,
  IconEye,
  IconFlame,
  IconFlower,
  IconFriends,
  IconGuitarPick,
  IconHeart,
  IconHeartbeat,
  IconHome,
  IconHourglass,
  IconLanguage,
  IconLeaf,
  IconMail,
  IconMapPin,
  IconMassage,
  IconMedicineSyrup,
  IconMedal,
  IconMessage,
  IconMicrophone,
  IconMoodCheck,
  IconMoodSmile,
  IconMoon,
  IconMusic,
  IconNews,
  IconNotebook,
  IconPaint,
  IconPalette,
  IconPencil,
  IconPhone,
  IconPigMoney,
  IconPill,
  IconPlane,
  IconPlant,
  IconPlant2,
  IconPlus,
  IconPray,
  IconQuestionMark,
  IconReceipt,
  IconRun,
  IconScale,
  IconSchool,
  IconShirt,
  IconShoppingCart,
  IconSoup,
  IconSparkles,
  IconStar,
  IconStethoscope,
  IconStretching,
  IconSunrise,
  IconSwimming,
  IconTargetArrow,
  IconTools,
  IconToolsKitchen2,
  IconTrash,
  IconTrees,
  IconTrophy,
  IconUserHeart,
  IconUsers,
  IconWalk,
  IconWash,
  IconWallet,
  IconWind,
  IconWriting,
  IconYoga,
  IconZzz,
  IconBrandYoutube,
} from "@tabler/icons-react-native";

export { HABIT_COLORS, UNIT_GROUPS, type HabitIconName };

type HabitIconComponent = ComponentType<{ color?: string; size?: number | string }>;

const RAW_ICON_MAP = {
  QuestionMark: IconQuestionMark,
  Plus: IconPlus,
  Run: IconRun,
  Walk: IconWalk,
  Yoga: IconYoga,
  Gym: IconBarbell,
  Cycling: IconBike,
  Heartbeat: IconHeartbeat,
  Flame: IconFlame,
  Energy: IconBolt,
  Brain: IconBrain,
  Book: IconBook,
  Journal: IconNotebook,
  Study: IconSchool,
  Focus: IconTargetArrow,
  Timer: IconClockHour4,
  Sparkles: IconSparkles,
  Language: IconLanguage,
  Moon: IconMoon,
  Water: IconDroplet,
  Heart: IconHeart,
  Apple: IconApple,
  Food: IconToolsKitchen2,
  Pill: IconPill,
  Dental: IconDental,
  Brush: IconBrush,
  Stethoscope: IconStethoscope,
  MoodSmile: IconMoodSmile,
  Work: IconBriefcase,
  Calendar: IconCalendarEvent,
  Checklist: IconChecklist,
  Mail: IconMail,
  Receipt: IconReceipt,
  Laptop: IconDeviceLaptop,
  Phone: IconDeviceMobile,
  Coding: IconCode,
  Money: IconCurrencyDollar,
  Savings: IconPigMoney,
  Wallet: IconWallet,
  Analytics: IconChartBar,
  Coffee: IconCoffee,
  Sunrise: IconSunrise,
  Bath: IconBath,
  Trash: IconTrash,
  Nature: IconTrees,
  Music: IconMusic,
  Travel: IconPlane,
  Home: IconHome,
  Bed: IconBed,
  Shopping: IconShoppingCart,
  Car: IconCar,
  Social: IconUsers,
  Chat: IconMessage,
  Call: IconPhone,
  Wind: IconWind,
  Cloud: IconCloud,
  Leaf: IconLeaf,
  Flower: IconFlower,
  Plant: IconPlant,
  Star: IconStar,
  Trophy: IconTrophy,
  Medal: IconMedal,
  Pencil: IconPencil,
  Camera: IconCamera,
  Palette: IconPalette,
  Microphone: IconMicrophone,
  ChefHat: IconChefHat,
  Gamepad: IconDeviceGamepad2,
  Pray: IconPray,
  Stretching: IconStretching,
  MoodCheck: IconMoodCheck,
  Alarm: IconAlarm,
  Award: IconAward,
  Football: IconBallFootball,
  Youtube: IconBrandYoutube,
  ChartLine: IconChartLine,
  ClipboardCheck: IconClipboardCheck,
  Confetti: IconConfetti,
  Eye: IconEye,
  Friends: IconFriends,
  Guitar: IconGuitarPick,
  Hourglass: IconHourglass,
  MapPin: IconMapPin,
  Massage: IconMassage,
  MedicineSyrup: IconMedicineSyrup,
  News: IconNews,
  Paint: IconPaint,
  Plant2: IconPlant2,
  Scale: IconScale,
  Shirt: IconShirt,
  Soup: IconSoup,
  Swimming: IconSwimming,
  Tools: IconTools,
  UserHeart: IconUserHeart,
  Wash: IconWash,
  Writing: IconWriting,
  Zzz: IconZzz,
} satisfies Record<HabitIconName, HabitIconComponent>;

export const ICON_MAP = RAW_ICON_MAP as Record<HabitIconName, HabitIconComponent>;

export interface HabitIcon {
  name: HabitIconName;
  icon: ElementType<{ color?: string; size?: number | string }>;
}

export interface HabitIconCategory {
  label: string;
  icons: HabitIcon[];
}

export const ICON_CATEGORIES: HabitIconCategory[] = HABIT_ICON_CATEGORIES.map(
  (category) => ({
    label: category.label,
    icons: category.iconNames.map((name) => ({
      name,
      icon: ICON_MAP[name],
    })),
  })
);
